### ISSUE TITLE
TestGoRoutineLeaks in manager_test.go Ocassionally Fails

### ISSUE THREAD

**Issue by Zalgo2462** [activecm/ipfix-rita#24]
Every once in a while TestGoRoutineLeaks fails.

**Comment by Zalgo2462** [comment]
I've put together a script to test this 

```
result="0"
while [ $result -eq "0" ]; do go test -run TestGoRoutineLeaks -v; result="$?"; done
```

This will run the test until it fails. Unfortunately, it doesn't seem to be failing on my machine. Looking at the test, there is a timeout of 15 seconds included in order to wait for the MongoDB driver to shut down. We may need to increase that timeout for some machines.

**Comment by Zalgo2462** [comment]
@enbake-dev Could you try increasing the 15 here to 20 and see if that fixes the problem?
https://github.com/activecm/ipfix-rita/blob/28c6ab8d2cde20eb87826f392fee0d58bfd8088a/converter/stitching/manager_test.go#L399

**Comment by enbake-dev** [comment]
I tried to put 20 in the time but still got it failed once while running the script whole day. Not sure but it might be memory problem
