### ISSUE TITLE
ipfix-rita script unable to launch

### ISSUE THREAD

**Issue by mer0llac0aster** [activecm/ipfix-rita#33]
Initialization script (**ipfix-rita)** looks for environment variables that don't exist, causing the script to fail to launch.

ERROR: Invalid interpolation format for "image" option in service "logstash": "quay.io/activecm/ipfix-rida-logstash:${IPFIX-RITA-VERSION:-latest}"

**Comment by Zalgo2462** [comment]
Hello, IPFIX-RITA is under heavy development. Thank you for your interest. A release will be posted to the github releases page when it becomes available for use.
