### ISSUE TITLE
init script ipfix-rita fails on docker-compose version

### ISSUE THREAD

**Issue by mer0llac0aster** [activecm/ipfix-rita#34]
Ubuntu 16.04 repo docker-compose cannot interpret version 3.3 in main.yaml. Need minimum required version for docker-compose to function.

**Comment by Zalgo2462** [comment]
Hello, thank you for your interest. 

The minimum supported versions of Docker and docker-compose are 17.06 and 1.16, respectively.

This project is not currently functional as it is waiting on changes to go through in the main RITA project. 

A release will be posted on the GitHub Releases page when things are working.
