### ISSUE TITLE
Bump RITA Output Version

### ISSUE THREAD

**Issue by Zalgo2462** [activecm/ipfix-rita#69]
RITA is moving to version 2.0. Thankfully, it appears the input schemas are backwards compatible. We will need to bump the ImportVersion version string in the MetaDatabase records we create to 2.0.

We might think about versioning the input schemas separate from the rest of the project to reduce this type of problem in the future. 

[This line](https://github.com/activecm/ipfix-rita/blob/master/converter/output/rita/database.go#L123) simply needs to be changed to: 
`	ImportVersion: "v2.0.0+ActiveCM-IPFIX",`

**Comment by SamuelCarroll** [comment]
There may be associated issues with this based on the new strope feature in RITA v2.0.0 we want to address as well
